### ISSUE TITLE
Stuck halfway

### ISSUE THREAD

**Issue by shaka-emperor** [NCGG-MGC/IMSindel#25]
Hi, I used following command to process 24 chromosome simultaneously:

cat 1.txt | parallel /home/IFNgroup/yejianyu/IMSindel/bin/imsindel --thread 1 --chr {} --bam /home/IFNgroup/yejianyu/Whloe_Genome_sequence/202201_WGS/data_process/P1_NORM_GRCh38_HBV.sort.bam --outd P1_Norm --indelsize 10000 --reffa /home/IFNgroup/yejianyu/ref/bwa_build_index/GRCh38.fa
(40 threads, 128 GB ram)

head 1.txt
chr1
chr2
chr3
chr4
chr5

While it gave me back 18 chromosomes output, there still had nothing for the rest 6 chromosomes.
And here is the last running message from IMSindel, I am not sure whether it is a warning message or not, but It stuck here for a week.

>2. collecting unmapped reads...done
>3. considering support reads...
#backward clip with support reads:      1684
#forward clip with support reads:       1575
#non_clips with suport reads:   4616
>3. considering support reads...done
>4. making consensus seqs from support reads...
v7.490 (2021/Oct/30)
mafft stderr:
outputhat23=16
treein = 0
compacttree = 0
stacksize: 8192 kb
generating a scoring matrix for nucleotide (dist=200) ... done
All-to-all alignment.
/home/yejianyu/anaconda3/bin/mafft: line 2756: 42213 Killed                  "$prefix/tbfast" _ -u $unalignlevel $localparam -C $numthreads $seqtype $model -g $lexp -f $lgop -Q $spfactor -h $laof -O $LGOP -E $LEXP -N $usenaivepairscore $focusarg _ -+ $iterate -W $minimumweight -V "-"$gopdist -s $unalignlevel $legacygapopt $mergearg $termgapopt $outnum $addarg $add2ndhalfarg -C $numthreadstb $rnaopt $weightopt $treeinopt $treeoutopt $distoutopt $seqtype $model -f "-"$gop -Q $spfactor -h $aof $param_fft $localparam $algopt $treealg $scoreoutarg $focusarg < infile > /dev/null 2>> "$progressfile"
#<Thread:0x000055c92855a360@/home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus.rb:84 run> terminated with exception (report_on_exception is true):
/home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus_util.rb:17:in `trim_consensus': undefined method `include?' for nil:NilClass (NoMethodError)
        from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus.rb:102:in `block in make_consensus'
        from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus.rb:100:in `each'
        from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus.rb:100:in `with_index'
        from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus.rb:100:in `make_consensus'
        from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus.rb:85:in `block (2 levels) in make_consensus_with_threads'
/home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus_util.rb:17:in `trim_consensus': undefined method `include?' for nil:NilClass (NoMethodError)
        from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus.rb:102:in `block in make_consensus'
        from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus.rb:100:in `each'
        from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus.rb:100:in `with_index'
        from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus.rb:100:in `make_consensus'
        from /home/IFNgroup/yejianyu/IMSindel/lib/ims_indel/consensus.rb:85:in `block (2 levels) in make_consensus_with_threads'

![image](https://user-images.githubusercontent.com/51046114/159109550-6b4b6c1e-144d-499b-bf2d-85994d099716.png)

**Comment by holrock** [comment]
It seems that mafft has terminated with an error.
IMSindel is failing to catch the error.
programs has stopped.
