### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by thedam** [NCGG-MGC/IMSindel#4]
Hi,
Sometimes the following error appear. I guess it happens when there are no reads mapped.

```
>3. considering support reads...done
>4. making consensus seqs from support reads...
Traceback (most recent call last):
        5: from /mnt/ssd_01/PROGRAMS/IMSindel/bin/imsindel:44:in `<main>'
        4: from /mnt/ssd_01/PROGRAMS/IMSindel/lib/ims_indel.rb:31:in `run'
        3: from /mnt/ssd_01/PROGRAMS/IMSindel/lib/ims_indel.rb:87:in `run_make_consensus_support_reads'
        2: from /mnt/ssd_01/PROGRAMS/IMSindel/lib/ims_indel/consensus.rb:32:in `make_support_read_consensus'
        1: from /mnt/ssd_01/PROGRAMS/IMSindel/lib/ims_indel/consensus.rb:77:in `make_consensus_with_threads'
/mnt/ssd_01/PROGRAMS/IMSindel/lib/ims_indel/consensus.rb:77:in `/': divided by 0 (ZeroDivisionError)
```

Regards
Damian

**Comment by holrock** [comment]
thanks for the report.
we'll fix that.
