### ISSUE TITLE
invalid slice size (ArgumentError)

### ISSUE THREAD

**Issue by thedam** [NCGG-MGC/IMSindel#6]
Hi,

the command:
`/IMSindel/bin/imsindel --bam xxxx.bam --chr chr13 --outd imsRawOuts/ --indelsize 10000 --reffa genome.fa`

the error:

```
>3. considering support reads...done
>4. making consensus seqs from support reads...
Traceback (most recent call last):
	5: from /mnt/ssd_01/PROGRAMS/IMSindel/bin/imsindel:44:in `<main>'
	4: from /mnt/ssd_01/PROGRAMS/IMSindel/lib/ims_indel.rb:31:in `run'
	3: from /mnt/ssd_01/PROGRAMS/IMSindel/lib/ims_indel.rb:87:in `run_make_consensus_support_reads'
	2: from /mnt/ssd_01/PROGRAMS/IMSindel/lib/ims_indel/consensus.rb:34:in `make_support_read_consensus'
	1: from /mnt/ssd_01/PROGRAMS/IMSindel/lib/ims_indel/consensus.rb:78:in `make_consensus_with_threads'
/mnt/ssd_01/PROGRAMS/IMSindel/lib/ims_indel/consensus.rb:78:in `each_slice': invalid slice size (ArgumentError)

```
(it is relatively small .bam file (137MB))

cheers
Damian

**Comment by holrock** [comment]
hello, I added size check. please update and try. thanks!

**Comment by thedam** [comment]
works:)
